[package]
name = "mykernel"
version = "0.1.0"
authors = ["Connor Postma <connor.postma@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.6.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"